version: "3"
services:
  backend_app:
    image: alinflorian81/idp_project_backend_server:latest
    links:
      - database
    ports:
      - "5000:5000"
    networks:
      - backend
  database:
    image: alinflorian81/idp_project_database:latest
    environment:
      MYSQL_ROOT_PASSWORD: "shortpass10"
    ports: 
      - "5001:3306"
    networks:
      - backend
networks:
  backend: