version: "3"
services:
  database:
    image: alinflorian81/idp_project_database:latest
    environment:
      MYSQL_ROOT_PASSWORD: "shortpass10"
    ports: 
      - "2000:3306"
    networks:
      - backend
      - upload
  backend_server:
    image: alinflorian81/idp_project_backend_server:latest
    ports:
      - "3000:5000"
    networks:
      - backend
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
  uploader:
    image: alinflorian81/idp_project_uploader:latest
    ports:
      - "4000:5000"
    networks:
      - upload
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  frontend_server:
    image: alinflorian81/idp_project_frontend_server:latest
    ports:
      - "5000:5000"
    networks:
      - frontend
      - upload
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
      - frontend
      - upload
networks:
  backend:
  frontend:
  upload: